// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://njaeohawnddtbsmnvphz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5qYWVvaGF3bmRkdGJzbW52cGh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NTE5NDQsImV4cCI6MjA3MDIyNzk0NH0.jNNvi7-jANNbmFc6IFJfEwJkPmzNEf54gahtvnwvd5s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});